QUOTES = [
    "Ship early, learn fast, iterate relentlessly.",
    "A program manager's job is to make the complex feel simple.",
    "Decisions should be made at the lowest level of competence.",
    "The best status update is a working product.",
    "Dependency management is risk management.",
    "Clarity of scope is clarity of purpose.",
    "Great TPMs don't manage tasks — they unblock teams.",
    "If you can't explain the timeline, you don't understand the project.",
    "Shipping is a muscle. The more you do it, the stronger you get.",
    "Every meeting without a decision is a meeting that should have been an email.",
    "Ambiguity is the enemy of execution.",
    "The roadmap is not the strategy. The strategy is why the roadmap exists.",
    "Cross-functional alignment is not optional — it is the job.",
    "Risk is not a spreadsheet. Risk is the thing nobody wants to talk about.",
    "A good launch is not the end. It is the first data point.",
    "Simplify the problem before you scale the solution.",
    "Your stakeholders don't need more updates. They need fewer surprises.",
    "The fastest way to fail is to build the wrong thing really well.",
    "Document the decision, not just the outcome.",
    "Execution without prioritization is just being busy.",
]
